### ISSUE TITLE
lisans hk.

### ISSUE THREAD

**Issue by ersin3381** [omercikan/Buzly-Ecommerce#1]
merhaba proje harika olmuş, projeyi kullanarak kendi e ticaret sitemizi açmamız mümkün mü yoksa lisans kısıtlamaları engel olur mu? teşekkürler.

**Comment by omercikan** [comment]
Merhaba, ilginiz için teşekkür ederim. Projeyi kullanarak kendi e-ticaret sitenizi açmanız mümkün değildir. Lisans koşullarımız, yazılımın yalnızca kişisel kullanım ve geliştirme amacıyla kullanılmasına izin verir. Ticari kullanım, lisans ihlali oluşturur ve <b>yasal sonuçlar doğurabilir.</b> Anlayışınız için teşekkür ederim.
